/*
 * Tokyo Afterimage — an original instrumental, 80 BPM / 32 bars / 96 seconds.
 * The bundled WAV is generated by scripts/ambient-score.js and includes an
 * eight-bar preroll to carry its reverb and sustained notes across the seam.
 * Native audio-buffer looping needs no background JavaScript scheduler.
 */
(() => {
  'use strict';

  const BPM = 80;
  const DURATION = 96;
  // Apply 2.5 times the previous 1.50 gain at the same volume setting.
  const MAX_OUTPUT_GAIN = 3.75;
  const TITLE = 'Tokyo Afterimage · 東京残像';
  const AUDIO_URL = new URL('./assets/tokyo-afterimage.wav', document.currentScript?.src || document.baseURI).href;
  const clamp = (value, low, high) => Math.max(low, Math.min(high, value));

  async function loadComposition(context) {
    const response = await fetch(AUDIO_URL, { cache: 'force-cache' });
    if (!response.ok) throw new Error('背景音乐文件读取失败');
    const buffer = await context.decodeAudioData(await response.arrayBuffer());
    if (buffer.numberOfChannels !== 2 || Math.abs(buffer.duration - DURATION) > 0.01) {
      throw new Error('背景音乐文件格式不正确');
    }
    let peak = 0;
    let squareSum = 0;
    for (let channel = 0; channel < buffer.numberOfChannels; channel++) {
      const samples = buffer.getChannelData(channel);
      for (let index = 0; index < samples.length; index++) {
        peak = Math.max(peak, Math.abs(samples[index]));
        squareSum += samples[index] * samples[index];
      }
    }
    const rms = Math.sqrt(squareSum / (buffer.length * buffer.numberOfChannels));
    if (!Number.isFinite(peak) || peak < 0.0001 || !Number.isFinite(rms)) {
      throw new Error('背景音乐文件无有效声音');
    }
    return { buffer, peak, rms };
  }

  function create({ onStatus } = {}) {
    let enabled = false;
    let volume = 90;
    let context = null;
    let output = null;
    let source = null;
    let rendered = null;
    let rendering = null;
    let pauseTimer = null;
    let suspension = null;
    let activated = false;
    let disposed = false;
    let startingAt = 0;
    let offset = 0;
    let state = 'paused';
    let error = null;
    const wanted = () => enabled && volume > 0 && !disposed;
    const getStatus = () => ({
      state,
      title: TITLE,
      musicEnabled: enabled,
      musicVolume: volume,
      contextState: context?.state || 'uninitialized',
      currentTime: context?.currentTime || 0,
      playbackSeconds: source ? (offset + Math.max(0, context.currentTime - startingAt)) % DURATION : offset,
      ready: Boolean(rendered),
      activeSources: source ? 1 : 0,
      tempoBpm: BPM,
      durationSeconds: DURATION,
      sampleRate: rendered?.buffer.sampleRate || null,
      peak: rendered?.peak || 0,
      rms: rendered?.rms || 0,
      error
    });
    function publish(next, message = null) {
      state = next;
      error = message;
      if (typeof onStatus === 'function') {
        try { onStatus(getStatus()); } catch (_) { /* UI callbacks must not stop audio. */ }
      }
    }
    function cancelPause() {
      if (pauseTimer !== null) window.clearTimeout(pauseTimer);
      pauseTimer = null;
    }
    function ensureContext() {
      if (context) return context;
      const Context = window.AudioContext || window.webkitAudioContext;
      if (!Context) throw new Error('此设备不支持背景音乐播放');
      context = new Context({ latencyHint: 'playback' });
      output = context.createGain();
      output.gain.value = 0;
      // Combine the boost and soft peak limiting within WaveShaper's [-1, 1]
      // input range. Quieter samples stay linear; loud peaks approach 0.98.
      const boost = context.createWaveShaper();
      const curve = new Float32Array(4097);
      for (let index = 0; index < curve.length; index++) {
        const value = (index * 2 / (curve.length - 1) - 1) * MAX_OUTPUT_GAIN;
        const magnitude = Math.abs(value);
        curve[index] = magnitude <= 0.90 ? value
          : Math.sign(value) * (0.90 + 0.08 * Math.tanh((magnitude - 0.90) / 0.08));
      }
      boost.curve = curve;
      boost.oversample = '4x';
      output.connect(boost);
      boost.connect(context.destination);
      context.onstatechange = () => {
        if (disposed) return;
        if (wanted() && source && context.state === 'running') publish('playing');
        else if (wanted() && context.state !== 'running' && state !== 'starting') publish('blocked');
        else if (!wanted()) publish('paused');
      };
      return context;
    }
    function fade(target, timeConstant) {
      if (!context || !output || context.state === 'closed') return;
      const now = context.currentTime;
      if (typeof output.gain.cancelAndHoldAtTime === 'function') output.gain.cancelAndHoldAtTime(now);
      else {
        output.gain.cancelScheduledValues(now);
        output.gain.setValueAtTime(output.gain.value, now);
      }
      output.gain.setTargetAtTime(target, now, timeConstant);
    }
    function stopSource() {
      if (!source) return;
      offset = (offset + Math.max(0, context.currentTime - startingAt)) % DURATION;
      try { source.stop(); } catch (_) { /* Already stopped during page close. */ }
      source.disconnect();
      source = null;
    }
    function pause() {
      cancelPause();
      fade(0, 0.10);
      publish('paused');
      if (!context || context.state === 'closed') return;
      // The fade is scheduled on the audio clock, even in a throttled window.
      pauseTimer = window.setTimeout(() => {
        pauseTimer = null;
        if (wanted() || disposed) return;
        stopSource();
        if (context.state === 'running') {
          suspension = context.suspend().catch(() => {}).finally(() => {
            suspension = null;
            if (!wanted() && !disposed) publish('paused');
          });
        } else publish('paused');
      }, 550);
    }
    async function start(resuming) {
      if (!wanted()) return;
      cancelPause();
      if (!activated) {
        publish('blocked');
        return;
      }
      if (source && context?.state === 'running') {
        fade(volume / 100, 0.12);
        publish('playing');
        return;
      }
      publish('starting');
      try {
        const ctx = ensureContext();
        // unlock() supplies the resume promise created within the user gesture.
        const resume = resuming || (ctx.state === 'running' ? Promise.resolve() : ctx.resume());
        if (!rendering && !rendered) {
          rendering = loadComposition(ctx).then(result => {
            if (!disposed) rendered = result;
            return result;
          }).catch(failure => {
            rendering = null;
            throw failure;
          });
        }
        await Promise.all([resume, rendered ? Promise.resolve(rendered) : rendering]);
        if (!wanted()) return;
        if (suspension) await suspension;
        if (!wanted()) return;
        if (ctx.state !== 'running') await ctx.resume();
        if (!wanted()) return;
        if (ctx.state !== 'running') {
          publish('blocked');
          return;
        }
        if (!source) {
          source = ctx.createBufferSource();
          source.buffer = rendered.buffer;
          source.loop = true;
          source.loopStart = 0;
          source.loopEnd = DURATION;
          source.connect(output);
          startingAt = ctx.currentTime;
          source.start(startingAt, offset);
        }
        fade(volume / 100, 0.32);
        publish('playing');
      } catch (failure) {
        if (disposed || !wanted()) return;
        const blocked = failure?.name === 'NotAllowedError' || context?.state === 'suspended';
        publish(blocked ? 'blocked' : 'error', blocked ? null : String(failure?.message || failure));
      }
    }
    function setPreferences(preferences = {}) {
      if (disposed) return;
      const nextEnabled = typeof preferences.musicEnabled === 'boolean' ? preferences.musicEnabled : enabled;
      const candidate = Number(preferences.musicVolume);
      const nextVolume = preferences.musicVolume !== undefined && Number.isFinite(candidate) ? clamp(candidate, 0, 100) : volume;
      if (enabled === nextEnabled && volume === nextVolume) return;
      enabled = nextEnabled;
      volume = nextVolume;
      if (wanted()) void start();
      else pause();
    }
    function unlock() {
      if (disposed) return Promise.resolve();
      // First interaction also primes the context if settings are still loading.
      if (activated && !wanted()) return Promise.resolve();
      if (activated && context?.state === 'running' && (source || state === 'starting')) return Promise.resolve();
      activated = true;
      let resuming;
      try {
        const ctx = ensureContext();
        resuming = ctx.state === 'running' ? Promise.resolve() : ctx.resume();
      } catch (failure) {
        publish('error', String(failure?.message || failure));
        return Promise.resolve();
      }
      if (wanted()) return start(resuming);
      return resuming.then(() => { if (!wanted() && !disposed) pause(); }).catch(() => {});
    }
    function dispose() {
      if (disposed) return;
      disposed = true;
      cancelPause();
      stopSource();
      if (context) {
        context.onstatechange = null;
        if (context.state !== 'closed') void context.close().catch(() => {});
      }
      if (output) output.disconnect();
      rendered = null;
      rendering = null;
      window.removeEventListener('pagehide', dispose);
      publish('paused');
    }
    window.addEventListener('pagehide', dispose, { once: true });
    return Object.freeze({ setPreferences, unlock, dispose, getStatus });
  }

  window.TokyoAmbience = Object.freeze({ create });
})();
