/*
 * Tokyo Afterimage — an original instrumental, 80 BPM / 32 bars / 96 seconds.
 * The bundled WAV is generated by scripts/ambient-score.js and includes an
 * eight-bar preroll to carry its reverb and sustained notes across the seam.
 * Native audio-buffer looping needs no background JavaScript scheduler.
 */
(() => {
  'use strict';

  const BPM = 80;
  const DURATION = 96;
  const SAMPLE_RATE = 44100;
  const METER_FRAMES = 32768;
  // The bundled track peaks below 0.64, leaving headroom at full volume.
  // Keep amplification linear: waveshaping its peaks makes the music distort.
  const MAX_OUTPUT_GAIN = 1.50;
  const TITLE = 'Tokyo Afterimage · 東京残像';
  const AUDIO_URL = new URL('./assets/tokyo-afterimage.wav', document.currentScript?.src || document.baseURI).href;
  const clamp = (value, low, high) => Math.max(low, Math.min(high, value));

  async function loadComposition(context) {
    const response = await fetch(AUDIO_URL, { cache: 'force-cache' });
    if (!response.ok) throw new Error('背景音乐文件读取失败');
    const buffer = await context.decodeAudioData(await response.arrayBuffer());
    if (buffer.numberOfChannels !== 2 || Math.abs(buffer.duration - DURATION) > 0.01) {
      throw new Error('背景音乐文件格式不正确');
    }
    let peak = 0;
    let squareSum = 0;
    let measured = 0;
    // These are diagnostic estimates, not a playback limiter. Sample across
    // the track instead of blocking the renderer on millions of PCM values.
    const stride = Math.max(1, Math.ceil(buffer.length / METER_FRAMES));
    for (let channel = 0; channel < buffer.numberOfChannels; channel++) {
      const samples = buffer.getChannelData(channel);
      for (let index = 0; index < samples.length; index += stride) {
        peak = Math.max(peak, Math.abs(samples[index]));
        squareSum += samples[index] * samples[index];
        measured++;
      }
    }
    const rms = Math.sqrt(squareSum / measured);
    if (!Number.isFinite(peak) || peak < 0.0001 || !Number.isFinite(rms)) {
      throw new Error('背景音乐文件无有效声音');
    }
    return { buffer, peak, rms };
  }

  function create({ onStatus } = {}) {
    let enabled = false;
    let volume = 90;
    let context = null;
    let output = null;
    let source = null;
    let rendered = null;
    let rendering = null;
    let pauseTimer = null;
    let suspension = null;
    let disposed = false;
    let startingAt = 0;
    let offset = 0;
    let state = 'paused';
    let error = null;
    const wanted = () => enabled && volume > 0 && !disposed;
    const getStatus = () => ({
      state,
      title: TITLE,
      musicEnabled: enabled,
      musicVolume: volume,
      contextState: context?.state || 'uninitialized',
      currentTime: context?.currentTime || 0,
      playbackSeconds: source ? (offset + Math.max(0, context.currentTime - startingAt)) % DURATION : offset,
      ready: Boolean(rendered),
      activeSources: source ? 1 : 0,
      tempoBpm: BPM,
      durationSeconds: DURATION,
      sampleRate: rendered?.buffer.sampleRate || null,
      peak: rendered?.peak || 0,
      rms: rendered?.rms || 0,
      error
    });
    function publish(next, message = null) {
      state = next;
      error = message;
      if (typeof onStatus === 'function') {
        try { onStatus(getStatus()); } catch (_) { /* UI callbacks must not stop audio. */ }
      }
    }
    function cancelPause() {
      if (pauseTimer !== null) window.clearTimeout(pauseTimer);
      pauseTimer = null;
    }
    function ensureContext() {
      if (context) return context;
      const Context = window.AudioContext || window.webkitAudioContext;
      if (!Context) throw new Error('此设备不支持背景音乐播放');
      // Decode at the bundled track's native rate instead of resampling the
      // entire 96-second buffer to the audio device's rate before first play.
      context = new Context({ latencyHint: 'playback', sampleRate: SAMPLE_RATE });
      output = context.createGain();
      output.gain.value = 0;
      output.connect(context.destination);
      context.onstatechange = () => {
        if (disposed) return;
        if (wanted() && source && context.state === 'running') publish('playing');
        else if (wanted() && context.state !== 'running' && state !== 'starting') publish('blocked');
        else if (!wanted()) publish('paused');
      };
      return context;
    }
    function fade(target, timeConstant) {
      if (!context || !output || context.state === 'closed') return;
      const now = context.currentTime;
      if (typeof output.gain.cancelAndHoldAtTime === 'function') output.gain.cancelAndHoldAtTime(now);
      else {
        output.gain.cancelScheduledValues(now);
        output.gain.setValueAtTime(output.gain.value, now);
      }
      output.gain.setTargetAtTime(target, now, timeConstant);
    }
    function stopSource() {
      if (!source) return;
      offset = (offset + Math.max(0, context.currentTime - startingAt)) % DURATION;
      try { source.stop(); } catch (_) { /* Already stopped during page close. */ }
      source.disconnect();
      source = null;
    }
    function pause() {
      cancelPause();
      fade(0, 0.10);
      publish('paused');
      if (!context || context.state === 'closed') return;
      // The fade is scheduled on the audio clock, even in a throttled window.
      pauseTimer = window.setTimeout(() => {
        pauseTimer = null;
        if (wanted() || disposed) return;
        stopSource();
        if (context.state === 'running') {
          suspension = context.suspend().catch(() => {}).finally(() => {
            suspension = null;
            if (!wanted() && !disposed) publish('paused');
          });
        } else publish('paused');
      }, 550);
    }
    async function start(resuming) {
      if (!wanted()) return;
      cancelPause();
      if (source && context?.state === 'running') {
        fade(volume / 100 * MAX_OUTPUT_GAIN, 0.12);
        publish('playing');
        return;
      }
      publish('starting');
      try {
        const ctx = ensureContext();
        // The desktop window allows autoplay. Resume and decode in parallel
        // as soon as the saved preferences enable music.
        const resume = resuming || (ctx.state === 'running' ? Promise.resolve() : ctx.resume());
        if (!rendering && !rendered) {
          rendering = loadComposition(ctx).then(result => {
            if (!disposed) rendered = result;
            return result;
          }).catch(failure => {
            rendering = null;
            throw failure;
          });
        }
        await Promise.all([resume, rendered ? Promise.resolve(rendered) : rendering]);
        if (!wanted()) return;
        if (suspension) await suspension;
        if (!wanted()) return;
        if (ctx.state !== 'running') await ctx.resume();
        if (!wanted()) return;
        if (ctx.state !== 'running') {
          publish('blocked');
          return;
        }
        if (!source) {
          source = ctx.createBufferSource();
          source.buffer = rendered.buffer;
          source.loop = true;
          source.loopStart = 0;
          source.loopEnd = DURATION;
          source.connect(output);
          startingAt = ctx.currentTime;
          source.start(startingAt, offset);
        }
        fade(volume / 100 * MAX_OUTPUT_GAIN, 0.32);
        publish('playing');
      } catch (failure) {
        if (disposed || !wanted()) return;
        const blocked = failure?.name === 'NotAllowedError' || context?.state === 'suspended';
        publish(blocked ? 'blocked' : 'error', blocked ? null : String(failure?.message || failure));
      }
    }
    function setPreferences(preferences = {}) {
      if (disposed) return;
      const nextEnabled = typeof preferences.musicEnabled === 'boolean' ? preferences.musicEnabled : enabled;
      const candidate = Number(preferences.musicVolume);
      const nextVolume = preferences.musicVolume !== undefined && Number.isFinite(candidate) ? clamp(candidate, 0, 100) : volume;
      if (enabled === nextEnabled && volume === nextVolume) return;
      enabled = nextEnabled;
      volume = nextVolume;
      if (wanted()) void start();
      else pause();
    }
    function unlock() {
      // A gesture may retry interrupted playback, but is never required to
      // start enabled music and must not activate disabled or muted music.
      if (!wanted()) return Promise.resolve();
      if (context?.state === 'running' && (source || state === 'starting')) return Promise.resolve();
      let resuming;
      try {
        const ctx = ensureContext();
        resuming = ctx.state === 'running' ? Promise.resolve() : ctx.resume();
      } catch (failure) {
        publish('error', String(failure?.message || failure));
        return Promise.resolve();
      }
      return start(resuming);
    }
    function dispose() {
      if (disposed) return;
      disposed = true;
      cancelPause();
      stopSource();
      if (context) {
        context.onstatechange = null;
        if (context.state !== 'closed') void context.close().catch(() => {});
      }
      if (output) output.disconnect();
      rendered = null;
      rendering = null;
      window.removeEventListener('pagehide', dispose);
      publish('paused');
    }
    window.addEventListener('pagehide', dispose, { once: true });
    return Object.freeze({ setPreferences, unlock, dispose, getStatus });
  }

  window.TokyoAmbience = Object.freeze({ create });
})();
